<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name_fr' => 'Afghanistan', 'name_en' => 'Afghanistan', 'code' => 'AF'],
            ['name_fr' => 'Afrique du Sud', 'name_en' => 'South Africa', 'code' => 'ZA'],
            ['name_fr' => 'Albanie', 'name_en' => 'Albania', 'code' => 'AL'],
            ['name_fr' => 'Algérie', 'name_en' => 'Algeria', 'code' => 'DZ'],
            ['name_fr' => 'Allemagne', 'name_en' => 'Germany', 'code' => 'DE'],
            ['name_fr' => 'Andorre', 'name_en' => 'Andorra', 'code' => 'AD'],
            ['name_fr' => 'Angola', 'name_en' => 'Angola', 'code' => 'AO'],
            ['name_fr' => 'Antigua-et-Barbuda', 'name_en' => 'Antigua and Barbuda', 'code' => 'AG'],
            ['name_fr' => 'Arabie Saoudite', 'name_en' => 'Saudi Arabia', 'code' => 'SA'],
            ['name_fr' => 'Argentine', 'name_en' => 'Argentina', 'code' => 'AR'],
            ['name_fr' => 'Arménie', 'name_en' => 'Armenia', 'code' => 'AM'],
            ['name_fr' => 'Australie', 'name_en' => 'Australia', 'code' => 'AU'],
            ['name_fr' => 'Autriche', 'name_en' => 'Austria', 'code' => 'AT'],
            ['name_fr' => 'Azerbaïdjan', 'name_en' => 'Azerbaijan', 'code' => 'AZ'],
            ['name_fr' => 'Bahamas', 'name_en' => 'Bahamas', 'code' => 'BS'],
            ['name_fr' => 'Bahreïn', 'name_en' => 'Bahrain', 'code' => 'BH'],
            ['name_fr' => 'Bangladesh', 'name_en' => 'Bangladesh', 'code' => 'BD'],
            ['name_fr' => 'Barbade', 'name_en' => 'Barbados', 'code' => 'BB'],
            ['name_fr' => 'Belgique', 'name_en' => 'Belgium', 'code' => 'BE'],
            ['name_fr' => 'Belize', 'name_en' => 'Belize', 'code' => 'BZ'],
            ['name_fr' => 'Bénin', 'name_en' => 'Benin', 'code' => 'BJ'],
            ['name_fr' => 'Bhoutan', 'name_en' => 'Bhutan', 'code' => 'BT'],
            ['name_fr' => 'Biélorussie', 'name_en' => 'Belarus', 'code' => 'BY'],
            ['name_fr' => 'Birmanie', 'name_en' => 'Myanmar', 'code' => 'MM'],
            ['name_fr' => 'Bolivie', 'name_en' => 'Bolivia', 'code' => 'BO'],
            ['name_fr' => 'Bosnie-Herzégovine', 'name_en' => 'Bosnia and Herzegovina', 'code' => 'BA'],
            ['name_fr' => 'Botswana', 'name_en' => 'Botswana', 'code' => 'BW'],
            ['name_fr' => 'Brésil', 'name_en' => 'Brazil', 'code' => 'BR'],
            ['name_fr' => 'Brunei', 'name_en' => 'Brunei', 'code' => 'BN'],
            ['name_fr' => 'Bulgarie', 'name_en' => 'Bulgaria', 'code' => 'BG'],
            ['name_fr' => 'Burkina Faso', 'name_en' => 'Burkina Faso', 'code' => 'BF'],
            ['name_fr' => 'Burundi', 'name_en' => 'Burundi', 'code' => 'BI'],
            ['name_fr' => 'Cambodge', 'name_en' => 'Cambodia', 'code' => 'KH'],
            ['name_fr' => 'Cameroun', 'name_en' => 'Cameroon', 'code' => 'CM'],
            ['name_fr' => 'Canada', 'name_en' => 'Canada', 'code' => 'CA'],
            ['name_fr' => 'Cap-Vert', 'name_en' => 'Cape Verde', 'code' => 'CV'],
            ['name_fr' => 'Centrafrique', 'name_en' => 'Central African Republic', 'code' => 'CF'],
            ['name_fr' => 'Chili', 'name_en' => 'Chile', 'code' => 'CL'],
            ['name_fr' => 'Chine', 'name_en' => 'China', 'code' => 'CN'],
            ['name_fr' => 'Chypre', 'name_en' => 'Cyprus', 'code' => 'CY'],
            ['name_fr' => 'Colombie', 'name_en' => 'Colombia', 'code' => 'CO'],
            ['name_fr' => 'Comores', 'name_en' => 'Comoros', 'code' => 'KM'],
            ['name_fr' => 'Congo-Brazzaville', 'name_en' => 'Republic of the Congo', 'code' => 'CG'],
            ['name_fr' => 'Congo-Kinshasa', 'name_en' => 'Democratic Republic of the Congo', 'code' => 'CD'],
            ['name_fr' => 'Corée du Nord', 'name_en' => 'North Korea', 'code' => 'KP'],
            ['name_fr' => 'Corée du Sud', 'name_en' => 'South Korea', 'code' => 'KR'],
            ['name_fr' => 'Costa Rica', 'name_en' => 'Costa Rica', 'code' => 'CR'],
            ['name_fr' => 'Croatie', 'name_en' => 'Croatia', 'code' => 'HR'],
            ['name_fr' => 'Cuba', 'name_en' => 'Cuba', 'code' => 'CU'],
            ['name_fr' => 'Danemark', 'name_en' => 'Denmark', 'code' => 'DK'],
            ['name_fr' => 'Djibouti', 'name_en' => 'Djibouti', 'code' => 'DJ'],
            ['name_fr' => 'Dominique', 'name_en' => 'Dominica', 'code' => 'DM'],
            ['name_fr' => 'Égypte', 'name_en' => 'Egypt', 'code' => 'EG'],
            ['name_fr' => 'Émirats arabes unis', 'name_en' => 'United Arab Emirates', 'code' => 'AE'],
            ['name_fr' => 'Équateur', 'name_en' => 'Ecuador', 'code' => 'EC'],
            ['name_fr' => 'Érythrée', 'name_en' => 'Eritrea', 'code' => 'ER'],
            ['name_fr' => 'Espagne', 'name_en' => 'Spain', 'code' => 'ES'],
            ['name_fr' => 'Estonie', 'name_en' => 'Estonia', 'code' => 'EE'],
            ['name_fr' => 'Eswatini', 'name_en' => 'Eswatini', 'code' => 'SZ'],
            ['name_fr' => 'États-Unis', 'name_en' => 'United States', 'code' => 'US'],
            ['name_fr' => 'Éthiopie', 'name_en' => 'Ethiopia', 'code' => 'ET'],
            ['name_fr' => 'Fidji', 'name_en' => 'Fiji', 'code' => 'FJ'],
            ['name_fr' => 'Finlande', 'name_en' => 'Finland', 'code' => 'FI'],
            ['name_fr' => 'France', 'name_en' => 'France', 'code' => 'FR'],
            ['name_fr' => 'Gabon', 'name_en' => 'Gabon', 'code' => 'GA'],
            ['name_fr' => 'Gambie', 'name_en' => 'Gambia', 'code' => 'GM'],
            ['name_fr' => 'Géorgie', 'name_en' => 'Georgia', 'code' => 'GE'],
            ['name_fr' => 'Ghana', 'name_en' => 'Ghana', 'code' => 'GH'],
            ['name_fr' => 'Grèce', 'name_en' => 'Greece', 'code' => 'GR'],
            ['name_fr' => 'Grenade', 'name_en' => 'Grenada', 'code' => 'GD'],
            ['name_fr' => 'Guatemala', 'name_en' => 'Guatemala', 'code' => 'GT'],
            ['name_fr' => 'Guinée', 'name_en' => 'Guinea', 'code' => 'GN'],
            ['name_fr' => 'Guinée-Bissau', 'name_en' => 'Guinea-Bissau', 'code' => 'GW'],
            ['name_fr' => 'Guinée équatoriale', 'name_en' => 'Equatorial Guinea', 'code' => 'GQ'],
            ['name_fr' => 'Guyana', 'name_en' => 'Guyana', 'code' => 'GY'],
            ['name_fr' => 'Haïti', 'name_en' => 'Haiti', 'code' => 'HT'],
            ['name_fr' => 'Honduras', 'name_en' => 'Honduras', 'code' => 'HN'],
            ['name_fr' => 'Hongrie', 'name_en' => 'Hungary', 'code' => 'HU'],
            ['name_fr' => 'Île Maurice', 'name_en' => 'Mauritius', 'code' => 'MU'],
            ['name_fr' => 'Inde', 'name_en' => 'India', 'code' => 'IN'],
            ['name_fr' => 'Indonésie', 'name_en' => 'Indonesia', 'code' => 'ID'],
            ['name_fr' => 'Irak', 'name_en' => 'Iraq', 'code' => 'IQ'],
            ['name_fr' => 'Iran', 'name_en' => 'Iran', 'code' => 'IR'],
            ['name_fr' => 'Irlande', 'name_en' => 'Ireland', 'code' => 'IE'],
            ['name_fr' => 'Islande', 'name_en' => 'Iceland', 'code' => 'IS'],
            ['name_fr' => 'Israël', 'name_en' => 'Israel', 'code' => 'IL'],
            ['name_fr' => 'Italie', 'name_en' => 'Italy', 'code' => 'IT'],
            ['name_fr' => 'Jamaïque', 'name_en' => 'Jamaica', 'code' => 'JM'],
            ['name_fr' => 'Japon', 'name_en' => 'Japan', 'code' => 'JP'],
            ['name_fr' => 'Jordanie', 'name_en' => 'Jordan', 'code' => 'JO'],
            ['name_fr' => 'Kazakhstan', 'name_en' => 'Kazakhstan', 'code' => 'KZ'],
            ['name_fr' => 'Kenya', 'name_en' => 'Kenya', 'code' => 'KE'],
            ['name_fr' => 'Kirghizistan', 'name_en' => 'Kyrgyzstan', 'code' => 'KG'],
            ['name_fr' => 'Kiribati', 'name_en' => 'Kiribati', 'code' => 'KI'],
            ['name_fr' => 'Koweït', 'name_en' => 'Kuwait', 'code' => 'KW'],
            ['name_fr' => 'Laos', 'name_en' => 'Laos', 'code' => 'LA'],
            ['name_fr' => 'Lesotho', 'name_en' => 'Lesotho', 'code' => 'LS'],
            ['name_fr' => 'Lettonie', 'name_en' => 'Latvia', 'code' => 'LV'],
            ['name_fr' => 'Liban', 'name_en' => 'Lebanon', 'code' => 'LB'],
            ['name_fr' => 'Libéria', 'name_en' => 'Liberia', 'code' => 'LR'],
            ['name_fr' => 'Libye', 'name_en' => 'Libya', 'code' => 'LY'],
            ['name_fr' => 'Liechtenstein', 'name_en' => 'Liechtenstein', 'code' => 'LI'],
            ['name_fr' => 'Lituanie', 'name_en' => 'Lithuania', 'code' => 'LT'],
            ['name_fr' => 'Luxembourg', 'name_en' => 'Luxembourg', 'code' => 'LU'],
            ['name_fr' => 'Macédoine du Nord', 'name_en' => 'North Macedonia', 'code' => 'MK'],
            ['name_fr' => 'Madagascar', 'name_en' => 'Madagascar', 'code' => 'MG'],
            ['name_fr' => 'Malaisie', 'name_en' => 'Malaysia', 'code' => 'MY'],
            ['name_fr' => 'Malawi', 'name_en' => 'Malawi', 'code' => 'MW'],
            ['name_fr' => 'Maldives', 'name_en' => 'Maldives', 'code' => 'MV'],
            ['name_fr' => 'Mali', 'name_en' => 'Mali', 'code' => 'ML'],
            ['name_fr' => 'Malte', 'name_en' => 'Malta', 'code' => 'MT'],
            ['name_fr' => 'Maroc', 'name_en' => 'Morocco', 'code' => 'MA'],
            ['name_fr' => 'Marshall', 'name_en' => 'Marshall Islands', 'code' => 'MH'],
            ['name_fr' => 'Mauritanie', 'name_en' => 'Mauritania', 'code' => 'MR'],
            ['name_fr' => 'Mexique', 'name_en' => 'Mexico', 'code' => 'MX'],
            ['name_fr' => 'Micronésie', 'name_en' => 'Micronesia', 'code' => 'FM'],
            ['name_fr' => 'Moldavie', 'name_en' => 'Moldova', 'code' => 'MD'],
            ['name_fr' => 'Monaco', 'name_en' => 'Monaco', 'code' => 'MC'],
            ['name_fr' => 'Mongolie', 'name_en' => 'Mongolia', 'code' => 'MN'],
            ['name_fr' => 'Monténégro', 'name_en' => 'Montenegro', 'code' => 'ME'],
            ['name_fr' => 'Mozambique', 'name_en' => 'Mozambique', 'code' => 'MZ'],
            ['name_fr' => 'Namibie', 'name_en' => 'Namibia', 'code' => 'NA'],
            ['name_fr' => 'Nauru', 'name_en' => 'Nauru', 'code' => 'NR'],
            ['name_fr' => 'Népal', 'name_en' => 'Nepal', 'code' => 'NP'],
            ['name_fr' => 'Nicaragua', 'name_en' => 'Nicaragua', 'code' => 'NI'],
            ['name_fr' => 'Niger', 'name_en' => 'Niger', 'code' => 'NE'],
            ['name_fr' => 'Nigeria', 'name_en' => 'Nigeria', 'code' => 'NG'],
            ['name_fr' => 'Niue', 'name_en' => 'Niue', 'code' => 'NU'],
            ['name_fr' => 'Norvège', 'name_en' => 'Norway', 'code' => 'NO'],
            ['name_fr' => 'Nouvelle-Zélande', 'name_en' => 'New Zealand', 'code' => 'NZ'],
            ['name_fr' => 'Oman', 'name_en' => 'Oman', 'code' => 'OM'],
            ['name_fr' => 'Ouganda', 'name_en' => 'Uganda', 'code' => 'UG'],
            ['name_fr' => 'Ouzbékistan', 'name_en' => 'Uzbekistan', 'code' => 'UZ'],
            ['name_fr' => 'Pakistan', 'name_en' => 'Pakistan', 'code' => 'PK'],
            ['name_fr' => 'Palaos', 'name_en' => 'Palau', 'code' => 'PW'],
            ['name_fr' => 'Palestine', 'name_en' => 'Palestine', 'code' => 'PS'],
            ['name_fr' => 'Panama', 'name_en' => 'Panama', 'code' => 'PA'],
            ['name_fr' => 'Papouasie-Nouvelle-Guinée', 'name_en' => 'Papua New Guinea', 'code' => 'PG'],
            ['name_fr' => 'Paraguay', 'name_en' => 'Paraguay', 'code' => 'PY'],
            ['name_fr' => 'Pays-Bas', 'name_en' => 'Netherlands', 'code' => 'NL'],
            ['name_fr' => 'Pérou', 'name_en' => 'Peru', 'code' => 'PE'],
            ['name_fr' => 'Philippines', 'name_en' => 'Philippines', 'code' => 'PH'],
            ['name_fr' => 'Pologne', 'name_en' => 'Poland', 'code' => 'PL'],
            ['name_fr' => 'Portugal', 'name_en' => 'Portugal', 'code' => 'PT'],
            ['name_fr' => 'Qatar', 'name_en' => 'Qatar', 'code' => 'QA'],
            ['name_fr' => 'République centrafricaine', 'name_en' => 'Central African Republic', 'code' => 'CF'],
            ['name_fr' => 'République dominicaine', 'name_en' => 'Dominican Republic', 'code' => 'DO'],
            ['name_fr' => 'République tchèque', 'name_en' => 'Czech Republic', 'code' => 'CZ'],
            ['name_fr' => 'Roumanie', 'name_en' => 'Romania', 'code' => 'RO'],
            ['name_fr' => 'Royaume-Uni', 'name_en' => 'United Kingdom', 'code' => 'GB'],
            ['name_fr' => 'Russie', 'name_en' => 'Russia', 'code' => 'RU'],
            ['name_fr' => 'Rwanda', 'name_en' => 'Rwanda', 'code' => 'RW'],
            ['name_fr' => 'Saint-Kitts-et-Nevis', 'name_en' => 'Saint Kitts and Nevis', 'code' => 'KN'],
            ['name_fr' => 'Sainte-Lucie', 'name_en' => 'Saint Lucia', 'code' => 'LC'],
            ['name_fr' => 'Saint-Vincent-et-les-Grenadines', 'name_en' => 'Saint Vincent and the Grenadines', 'code' => 'VC'],
            ['name_fr' => 'Salvador', 'name_en' => 'El Salvador', 'code' => 'SV'],
            ['name_fr' => 'Samoa', 'name_en' => 'Samoa', 'code' => 'WS'],
            ['name_fr' => 'Sao Tomé-et-Principe', 'name_en' => 'Sao Tome and Principe', 'code' => 'ST'],
            ['name_fr' => 'Sénégal', 'name_en' => 'Senegal', 'code' => 'SN'],
            ['name_fr' => 'Serbie', 'name_en' => 'Serbia', 'code' => 'RS'],
            ['name_fr' => 'Seychelles', 'name_en' => 'Seychelles', 'code' => 'SC'],
            ['name_fr' => 'Sierra Leone', 'name_en' => 'Sierra Leone', 'code' => 'SL'],
            ['name_fr' => 'Singapour', 'name_en' => 'Singapore', 'code' => 'SG'],
            ['name_fr' => 'Slovaquie', 'name_en' => 'Slovakia', 'code' => 'SK'],
            ['name_fr' => 'Slovénie', 'name_en' => 'Slovenia', 'code' => 'SI'],
            ['name_fr' => 'Somalie', 'name_en' => 'Somalia', 'code' => 'SO'],
            ['name_fr' => 'Soudan', 'name_en' => 'Sudan', 'code' => 'SD'],
            ['name_fr' => 'Soudan du Sud', 'name_en' => 'South Sudan', 'code' => 'SS'],
            ['name_fr' => 'Sri Lanka', 'name_en' => 'Sri Lanka', 'code' => 'LK'],
            ['name_fr' => 'Suède', 'name_en' => 'Sweden', 'code' => 'SE'],
            ['name_fr' => 'Suisse', 'name_en' => 'Switzerland', 'code' => 'CH'],
            ['name_fr' => 'Suriname', 'name_en' => 'Suriname', 'code' => 'SR'],
            ['name_fr' => 'Syrie', 'name_en' => 'Syria', 'code' => 'SY'],
            ['name_fr' => 'Tadjikistan', 'name_en' => 'Tajikistan', 'code' => 'TJ'],
            ['name_fr' => 'Tanzanie', 'name_en' => 'Tanzania', 'code' => 'TZ'],
            ['name_fr' => 'Tchad', 'name_en' => 'Chad', 'code' => 'TD'],
            ['name_fr' => 'Thaïlande', 'name_en' => 'Thailand', 'code' => 'TH'],
            ['name_fr' => 'Timor oriental', 'name_en' => 'Timor-Leste', 'code' => 'TL'],
            ['name_fr' => 'Togo', 'name_en' => 'Togo', 'code' => 'TG'],
            ['name_fr' => 'Tonga', 'name_en' => 'Tonga', 'code' => 'TO'],
            ['name_fr' => 'Trinité-et-Tobago', 'name_en' => 'Trinidad and Tobago', 'code' => 'TT'],
            ['name_fr' => 'Tunisie', 'name_en' => 'Tunisia', 'code' => 'TN'],
            ['name_fr' => 'Turkménistan', 'name_en' => 'Turkmenistan', 'code' => 'TM'],
            ['name_fr' => 'Turquie', 'name_en' => 'Turkey', 'code' => 'TR'],
            ['name_fr' => 'Tuvalu', 'name_en' => 'Tuvalu', 'code' => 'TV'],
            ['name_fr' => 'Ukraine', 'name_en' => 'Ukraine', 'code' => 'UA'],
            ['name_fr' => 'Uruguay', 'name_en' => 'Uruguay', 'code' => 'UY'],
            ['name_fr' => 'Vanuatu', 'name_en' => 'Vanuatu', 'code' => 'VU'],
            ['name_fr' => 'Vatican', 'name_en' => 'Vatican City', 'code' => 'VA'],
            ['name_fr' => 'Venezuela', 'name_en' => 'Venezuela', 'code' => 'VE'],
            ['name_fr' => 'Viêt Nam', 'name_en' => 'Vietnam', 'code' => 'VN'],
            ['name_fr' => 'Yémen', 'name_en' => 'Yemen', 'code' => 'YE'],
            ['name_fr' => 'Zambie', 'name_en' => 'Zambia', 'code' => 'ZM'],
            ['name_fr' => 'Zimbabwe', 'name_en' => 'Zimbabwe', 'code' => 'ZW'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
